# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 719)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 190, 640, 360))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(770, 180, 171, 381))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 671, 151))
        self.layoutWidget.setMinimumSize(QtCore.QSize(40, 60))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_pt = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_pt.setMinimumSize(QtCore.QSize(40, 60))
        self.pushButton_pt.setObjectName("pushButton_pt")
        self.horizontalLayout.addWidget(self.pushButton_pt)
        self.pushButton_init = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_init.setMinimumSize(QtCore.QSize(40, 60))
        self.pushButton_init.setObjectName("pushButton_init")
        self.horizontalLayout.addWidget(self.pushButton_init)
        self.pushButton_sht = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_sht.setMinimumSize(QtCore.QSize(40, 60))
        self.pushButton_sht.setObjectName("pushButton_sht")
        self.horizontalLayout.addWidget(self.pushButton_sht)
        self.pushButton_exit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(40, 60))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout.addWidget(self.pushButton_exit)
        self.pushButton_setting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setting.setEnabled(True)
        self.pushButton_setting.setGeometry(QtCore.QRect(770, 70, 162, 60))
        self.pushButton_setting.setObjectName("pushButton_setting")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1027, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "yolov7手勢操作電腦系統"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_pt.setText(_translate("MainWindow", "Select weights"))
        self.pushButton_init.setText(_translate("MainWindow", "Model initialize"))
        self.pushButton_sht.setText(_translate("MainWindow", "Open Camera"))
        self.pushButton_exit.setText(_translate("MainWindow", "Stop(video)"))
        self.pushButton_setting.setText(_translate("MainWindow", "Setting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
